name: ReVanced Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download Stored base APKs
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          tag: 'base'
          fileName: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APKs
        run: ./build_revanced.sh
              
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK's
        with:
          releaseDirectory: build
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          output: build/release/signed
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
        env:
          BUILD_TOOLS_VERSION: "30.0.2"     
          
      - name: Generate SHA256 checksums for the signed APK files
        run: ./generate-SHA256sum.sh
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release ${{ env.date_now }}"
          files: |
            build/SHA-256.txt
            build/*signed*.apk
            vanced-microG.apk